<?php

declare(strict_types=1);

/*
 * WeatherAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WeatherAPILib\Controllers;

use WeatherAPILib\Exceptions\ApiException;
use WeatherAPILib\ApiHelper;
use WeatherAPILib\ConfigurationInterface;
use WeatherAPILib\Http\HttpRequest;
use WeatherAPILib\Http\HttpResponse;
use WeatherAPILib\Http\HttpMethod;
use WeatherAPILib\Http\HttpContext;
use WeatherAPILib\Http\HttpCallBack;
use Unirest\Request;

class SimpleWeatherController extends BaseController
{
    public function __construct(ConfigurationInterface $config, array $authManagers, ?HttpCallBack $httpCallBack)
    {
        parent::__construct($config, $authManagers, $httpCallBack);
    }

    /**
     * @param string $q city name
     *
     * @return void Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function weather(string $q): void
    {
        //prepare query string for API call
        $_queryBuilder = '/';

        //process optional query parameters
        ApiHelper::appendUrlWithQueryParameters($_queryBuilder, [
            'appid' => '08968633aa51dd1439ba6625a94937c5',
            'q'     => $q,
        ]);

        //validate and preprocess url
        $_queryUrl = ApiHelper::cleanUrl($this->config->getBaseUri() . $_queryBuilder);

        //prepare headers
        $_headers = [
            'user-agent'    => BaseController::USER_AGENT
        ];

        $_httpRequest = new HttpRequest(HttpMethod::GET, $_headers, $_queryUrl);

        // Apply authorization to request
        $this->getAuthManager('global')->apply($_httpRequest);

        //call on-before Http callback
        if ($this->getHttpCallBack() != null) {
            $this->getHttpCallBack()->callOnBeforeRequest($_httpRequest);
        }

        // Set request timeout
        Request::timeout($this->config->getTimeout());

        // and invoke the API call request to fetch the response
        try {
            $response = Request::get($_httpRequest->getQueryUrl(), $_httpRequest->getHeaders());
        } catch (\Unirest\Exception $ex) {
            throw new ApiException($ex->getMessage(), $_httpRequest);
        }


        $_httpResponse = new HttpResponse($response->code, $response->headers, $response->raw_body);
        $_httpContext = new HttpContext($_httpRequest, $_httpResponse);

        //call on-after Http callback
        if ($this->getHttpCallBack() != null) {
            $this->getHttpCallBack()->callOnAfterRequest($_httpContext);
        }

        //handle errors defined at the API level
        $this->validateResponse($_httpResponse, $_httpRequest);
    }
}
